name: ynovml_env
channels:
  - conda-forge
dependencies:
  - python==3.6.12
  - ipykernel==5.3.4
  - eli5==0.11.0
  - pdpbox==0.2.0
  - shap==0.37.0
  - scikit-learn==0.24.1
  - matplotlib==3.3.4
  - pandas==1.1.3
  - seaborn==0.11.0
  - pip==20.3.3